/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

/**
 *
 * @author dsi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        toggleObj = new javax.swing.JToggleButton();
        toggleInf = new javax.swing.JToggleButton();
        toggleAide = new javax.swing.JToggleButton();
        toggleRecap = new javax.swing.JToggleButton();
        toggleDeco = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Ecran Principal");

        toggleObj.setText("Objectifs");
        toggleObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleObjActionPerformed(evt);
            }
        });

        toggleInf.setText("Informations");
        toggleInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleInfActionPerformed(evt);
            }
        });

        toggleAide.setText("Aide");
        toggleAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAideActionPerformed(evt);
            }
        });

        toggleRecap.setText("Récapitulatif");
        toggleRecap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRecapActionPerformed(evt);
            }
        });

        toggleDeco.setText("Déconnexion");
        toggleDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleDecoActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toggleRecap)
                            .addComponent(toggleDeco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(toggleAide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toggleObj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toggleInf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(toggleObj)
                .addGap(18, 18, 18)
                .addComponent(toggleInf)
                .addGap(18, 18, 18)
                .addComponent(toggleAide)
                .addGap(18, 18, 18)
                .addComponent(toggleRecap)
                .addGap(18, 18, 18)
                .addComponent(toggleDeco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void toggleDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleDecoActionPerformed
        // TODO add your handling code here:
       Connexion c = new Connexion();
       c.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_toggleDecoActionPerformed

    private void toggleObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleObjActionPerformed
        // TODO add your handling code here:
       Objectifs o = new Objectifs();
       o.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_toggleObjActionPerformed

    private void toggleAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAideActionPerformed
        this.setVisible(false);
        new Help().setVisible(true);
    }//GEN-LAST:event_toggleAideActionPerformed

    private void toggleInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleInfActionPerformed
        // TODO add your handling code here:
       Infos i = new Infos();
       i.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_toggleInfActionPerformed

    private void toggleRecapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRecapActionPerformed
        // TODO add your handling code here:
       Recap r = new Recap();
       r.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_toggleRecapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton toggleAide;
    private javax.swing.JToggleButton toggleDeco;
    private javax.swing.JToggleButton toggleInf;
    private javax.swing.JToggleButton toggleObj;
    private javax.swing.JToggleButton toggleRecap;
    // End of variables declaration//GEN-END:variables
}
